name: "test"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      #with:
      #ref: output
    - uses: ./
      with:
        url: https://magento.taku.pw/
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: main
        file_pattern: images
        commit_message: save screenshot
